### PR TITLE
Issue #1193 normalize menu links

### PR DESCRIPTION
**Pull request by gielfeldt**

### CODE REVIEW

**Comment by cableman** [comment]
Please update commit messages with "git rebase" to follow the format:

Issue #1193 by gielfeldt: Message

**Comment by xendk** [comment]
Considering we're using inbound_alter, how about using outbound_alter and skip the href munging?

**Comment by gielfeldt** [comment]
I did try with outbound_alter(). However, either it didn't work as expected, or it wasn't performant. I can't remember. And I didn't take a note.

**Comment by xendk** [comment]
Dude... Replacing uid with "me" is the bloody example of using outbound_alter: https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_url_outbound_alter/7

**Comment by xendk** [comment]
So, @gielfeldt notes that it was @kasperg's idea to not use outbound_alter, @kasperg cites "performance reasons", so I ran some simple benchmarks.

A vanilla Ding2 uses about 1 ms per 100 links on outbound altering. Most of that is eaten by locale.modules https://api.drupal.org/api/drupal/modules%21locale%21locale.module/function/locale_url_outbound_alter/7

Implementing as slightly modified version of the example from the outbound_alter doc page (which could be optimized) only shifts the number by something like 300 µs per 100 links.

I don't think sacrificing the symmetry of outbound/inbound on the Altar of Performance is justified in this case.

**Comment by gielfeldt** [comment]
@xendk I don't recall saying quite that? However, if you feel that using hook_url_outbound_alter() is a better solution, you are welcome to update the pull-request.

**Comment by xendk** [comment]
I don't have logfiles on voice, but I seem to remember that you said something about using outbound_alter at first, but changing it after talking with @kasperg. If that's not what you said, I'm sorry, but I got the impression that you didn't feel particularly strongly for the issue. I was just attempting to leave a breadcrumb for the next person dealing with this issue, as to who might have a strong opinion on the matter...

I'm just trying to leave history for whoever gets to rewrite this as a PR aganst the consolidated ding2, no guarantees that I get there first.

**Comment by xendk** [comment]
Fixed in core, @kasperg can you close this to eliminate future confusion?

**Pull request closed without merging**
